// Generated by scripts/gen-registry.ts. Do not edit; run `pnpm gen:registry`.
import type { AnyGameDefinition } from '@games/game-sdk';
import game0 from '@games/game-liars-dice/server';

export const games: readonly AnyGameDefinition[] = [game0];
