// Generated by scripts/gen-registry.ts. Do not edit; run `pnpm gen:registry`.
import type { GameManifest } from '@games/game-sdk';
import manifest0 from '@games/game-liars-dice/manifest';
import manifest1 from '@games/game-who-dat/manifest';

export const manifests: readonly GameManifest[] = [manifest0, manifest1];
