/**
 * Wires every package in packages/games/* into the apps, so adding a game never means editing
 * platform code. Writes the generated registry files and keeps each app's dependencies in sync.
 *
 * Usage: pnpm gen:registry   (also run by `pnpm new-game` and before dev/build)
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(import.meta.dirname, '..');

interface Target {
  app: string;
  file: string;
  render(games: GamePackage[]): string;
}

interface GamePackage {
  id: string;
  packageName: string;
}

const header = '// Generated by scripts/gen-registry.ts. Do not edit; run `pnpm gen:registry`.\n';

const targets: Target[] = [
  {
    app: 'apps/game-server',
    file: 'src/games.gen.ts',
    render: (games) =>
      `${header}import type { AnyGameDefinition } from '@games/game-sdk';\n` +
      games.map((g, i) => `import game${i} from '${g.packageName}/server';\n`).join('') +
      `\nexport const games: readonly AnyGameDefinition[] = [${games.map((_, i) => `game${i}`).join(', ')}];\n`,
  },
  {
    // Manifests are plain data: safe for server components and static pages.
    app: 'apps/web',
    file: 'src/games.gen.ts',
    render: (games) =>
      `${header}import type { GameManifest } from '@games/game-sdk';\n` +
      games.map((g, i) => `import manifest${i} from '${g.packageName}/manifest';\n`).join('') +
      `\nexport const manifests: readonly GameManifest[] = [${games.map((_, i) => `manifest${i}`).join(', ')}];\n`,
  },
  {
    // Game UIs are only loaded on the client, and only when that game is opened.
    app: 'apps/web',
    file: 'src/game-clients.gen.ts',
    render: (games) =>
      `${header}import type { GameComponent } from '@games/game-sdk/client';\n\n` +
      'export const gameClients: Record<string, () => Promise<{ default: GameComponent }>> = {\n' +
      games.map((g) => `  '${g.id}': () => import('${g.packageName}/client'),\n`).join('') +
      '};\n',
  },
];

export function findGames(): GamePackage[] {
  const dir = join(root, 'packages/games');
  if (!existsSync(dir)) return [];
  return readdirSync(dir, { withFileTypes: true })
    .filter((entry) => entry.isDirectory() && existsSync(join(dir, entry.name, 'package.json')))
    .map((entry) => {
      const pkg = JSON.parse(readFileSync(join(dir, entry.name, 'package.json'), 'utf8'));
      return { id: entry.name, packageName: pkg.name as string };
    })
    .sort((a, b) => a.id.localeCompare(b.id));
}

/** Returns true when an app's package.json changed and `pnpm install` is needed. */
export function generateRegistry(): boolean {
  const games = findGames();
  let dependenciesChanged = false;

  for (const target of targets) {
    const appDir = join(root, target.app);
    if (!existsSync(appDir)) continue;

    const file = join(appDir, target.file);
    const content = target.render(games);
    if (!existsSync(file) || readFileSync(file, 'utf8') !== content) writeFileSync(file, content);

    const pkgPath = join(appDir, 'package.json');
    const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'));
    const deps: Record<string, string> = { ...pkg.dependencies };
    for (const name of Object.keys(deps)) {
      if (
        name.startsWith('@games/game-') &&
        name !== '@games/game-sdk' &&
        name !== '@games/game-server'
      ) {
        if (!games.some((g) => g.packageName === name)) delete deps[name];
      }
    }
    for (const game of games) deps[game.packageName] = 'workspace:*';
    const sorted = Object.fromEntries(Object.entries(deps).sort(([a], [b]) => a.localeCompare(b)));
    if (JSON.stringify(sorted) !== JSON.stringify(pkg.dependencies ?? {})) {
      pkg.dependencies = sorted;
      writeFileSync(pkgPath, `${JSON.stringify(pkg, null, 2)}\n`);
      dependenciesChanged = true;
    }
  }

  console.log(
    `Registry: ${games.length} game(s)${games.length ? `: ${games.map((g) => g.id).join(', ')}` : ''}`,
  );
  return dependenciesChanged;
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  if (generateRegistry()) console.log('App dependencies changed; run `pnpm install`.');
}
